---
version: 2.1

setup: true

orbs:
  orb-tools: circleci/orb-tools@12.1.0
  shellcheck: circleci/shellcheck@3.2.0

globals:
  - &context orb-publishing
  - &orb-name twdps/python-api

on-push-main: &on-push-main
  branches:
    only: /main/
  tags:
    ignore: /.*/

on-tag-main: &on-tag-main
  branches:
    ignore: /.*/
  tags:
    only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

workflows:

  static analysis and test:
    jobs:
      - orb-tools/lint:
          filters: *on-push-main

      - orb-tools/review:
          exclude: RC010,RC009
          filters: *on-push-main

      - shellcheck/check:
          filters: *on-push-main

      - orb-tools/pack:
          filters: *on-push-main

      - orb-tools/publish:
          name: publish development package
          context: *context
          orb_name: *orb-name
          vcs_type: << pipeline.project.type >>
          filters: *on-push-main
          requires:
            - orb-tools/lint
            - orb-tools/review
            - shellcheck/check
            - orb-tools/pack
