# src/commands/build.yaml
# yamllint disable rule:line-length
---

description: Build oci compatible image from Dockerfile.

parameters:

  dockerfile:
    description: Name of dockerfile.
    type: string
    default: Dockerfile

  path:
    description: Path to the directory containing your Dockerfile and build context.
    type: string
    default: .

  image:
    description: Name of image.
    type: string

  tag:
    description: Value for tag.
    type: string
    default: dev.${CIRCLE_SHA1:0:7}

  registry:
    description: Name of registry.
    type: string
    default: docker.io

  extra-build-args:
    description: >
      (Optional) Extra flags to pass to docker build. For examples, see
      https://docs.docker.com/engine/reference/commandline/build
    type: string
    default: ""

steps:
  - run:
      name: Docker Build
      command: |
        str="<< parameters.image >>.<< parameters.tag >>.build.out"
        outfile=${str#*/}
        docker -v
        docker build \
          <<#parameters.extra-build-args>><<parameters.extra-build-args>><</parameters.extra-build-args>> \
          -t << parameters.registry >>/<< parameters.image >>:<< parameters.tag >> \
          -f << parameters.dockerfile >> << parameters.path >> 2>&1 | tee workspace/$outfile
