# src/commands/configure-machine.yaml

description: Install additional tools on standard circleci ubuntu machine executor for docker build and test.

parameters:

  op-version:
    description: Set to install 1password cli
    type: string
    default: ""

steps:
  - when:
      condition: << parameters.op-version >>
      steps:
        - run:
            name: install 1password
            command: |
              curl -L https://cache.agilebits.com/dist/1P/op2/pkg/v<< parameters.op-version >>/op_linux_amd64_v<< parameters.op-version >>.zip -o op.zip
              unzip -o op.zip && sudo mv op /usr/local/bin/op
              rm op.zip && rm op.sig
              op --version


  # - run:
  #     name: install snyk
  #     command: npm install -g snyk
