# src/commands/configure-machine.yaml

description: |
  Install additional tools on standard circleci ubuntu machine executor.

parameters:

  python-version:
    description: version of python to install. 3 and above.
    type: string

  setuptools-version:
    type: string

  wheel-version:
    type: string

  pipenv-version:
    type: string

  pylint-version:
    type: string

  pytest-version:
    type: string

  coverage-version:
    type: string

  invoke-version:
    type: string

  requests-version:
    type: string

  jinja2-version:
    type: string


steps:
  - run:
      name: install python version via pyenv
      command: pyenv install << parameters.python-version >>
  - run:
      name: install default python packages
      command: |
        pip install \
            setuptools==<< parameters.setuptools-version >> \
            wheel==<< parameters.wheel-version >> \
            pipenv==<< parameters.pipenv-version >> \
            pylint==<< parameters.pylint-version >> \
            pytest==<< parameters.pytest-version >> \
            coverage==<< parameters.coverage-version >> \
            invoke==<< parameters.invoke-version >> \
            requests==<< parameters.requests-version >> \
            jinja2==<< parameters.jinja2-version >>
  - run:
      name: install codeclimate test coverage report-coverage
      command: |
        sudo bash -c "curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > /usr/local/bin/cc-test-reporter"
        sudo chmod +x /usr/local/bin/cc-test-reporter
  - run:
      name: install secrethub
      command: |
        curl -sLJO https://deb.secrethub.io/amd64
        sudo dpkg -i secrethub-cli-amd64.deb
  - run:
      name: install snyk
      command: npm install -g snyk
